---
minimum_prek_version: "0.3.0"

pypi_index: &pypi_index "--index-url=https://pypi.org/simple"

default_install_hook_types:
  - pre-commit
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-illegal-windows-names

      - id: check-added-large-files
        additional_dependencies: [*pypi_index]

      - id: check-ast
        additional_dependencies: [*pypi_index]

      - id: check-case-conflict
        additional_dependencies: [*pypi_index]

      - id: check-executables-have-shebangs
        additional_dependencies: [*pypi_index]

      - id: check-json
        additional_dependencies: [*pypi_index]

      - id: check-symlinks
        additional_dependencies: [*pypi_index]

      - id: check-toml
        additional_dependencies: [*pypi_index]

      - id: check-yaml
        additional_dependencies: [*pypi_index]

      - id: destroyed-symlinks
        additional_dependencies: [*pypi_index]

      - id: detect-private-key
        additional_dependencies: [*pypi_index]

      - id: end-of-file-fixer
        additional_dependencies: [*pypi_index]

      - id: mixed-line-ending
        additional_dependencies: [*pypi_index]

      - id: trailing-whitespace
        additional_dependencies: [*pypi_index]

      - id: name-tests-test
        args: [--pytest-test-first]
        additional_dependencies: [*pypi_index]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix]
        additional_dependencies: [*pypi_index]

      - id: ruff-format
        args: [--exit-non-zero-on-format]
        additional_dependencies: [*pypi_index]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.3
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: [*pypi_index, "bandit[toml]"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - *pypi_index
          - flake8-pydantic
          - flake8-pyproject
          - wemake-python-styleguide

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
        additional_dependencies: [*pypi_index, nodejs]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.27
    hooks:
      - id: uv-lock
        additional_dependencies: [*pypi_index]

      - id: uv-sync
        additional_dependencies: [*pypi_index]

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v0.7.25
    hooks:
      - id: tombi-format
        additional_dependencies: [*pypi_index]

      - id: tombi-lint
        additional_dependencies: [*pypi_index]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        require_serial: true
        args: [--config-file, pyproject.toml]
        stages:
          - pre-commit
          - pre-push
          - manual
